openai:
  api_key: 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
  model: "text-davinci-003"
  parameters:
    suffix: null
    max_tokens: 1024
    temperature: 1
    top_p: 1
    n: 1
    stream: false
    logprobs: null
    echo: false
    stop: \n
    presence_penalty: 0
    frequency_penalty: 0
    best_of: 1
    logit_bias: null
